# PonePaste NGINX configuration for local development on Arch Linux; not intended for production usage!
server {
    listen 80;
    root /srv/http/ponepaste.local;
    index index.html index.php;

    server_name ponepaste.local;

    rewrite ^/$ /index.php last;
    rewrite ^/([0-9]+)$ /paste.php?id=$1 last;
    rewrite ^/page/([a-zA-Z0-9]+)/?$ /pages.php?page=$1 last;

    # simple routes that just map to $1.php
    rewrite ^/(archive|discover|profile|contact|report|event|captcha|login|logout)/?$ /$1.php last;

    # routes for users
    rewrite ^/user/([^/]+)/?$ /user.php?user=$1 last;
    rewrite ^/user/([^/]+)/([^/]+)/?$ /user.php?user=$1&q=$2 last;

    # routes for pastes
    rewrite ^/(download|raw|embed)/(.+)$ /paste.php?$1&id=$2 last;

    # weird registration routes that use a URL parameter rather than a different page (FIXME)
    rewrite ^/register$ /login.php last;
    rewrite ^/forgot$ /login.php last;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/run/php/php-fpm.sock;
    }

    # Deny directories that should not be publicly accessible.
    location ~ (/doc|/tmp|/includes|/config|/\.git|/\.ht|/js|/node_modules|/composer).* {
        deny all;
    }
}
