# PonePaste NGINX configuration for local development on Arch Linux; not intended for production usage!
server {
    listen 80;
    root /srv/http/ponepaste.local;
    index index.html index.php;

    server_name ponepaste.local;
    
    error_log /var/log/nginx/ponepaste.local_error.log;
    # misc / generic routes
    rewrite ^/$ /index.php last;
    rewrite ^/page/([a-zA-Z0-9]+)/?$ /pages.php?page=$1 last;

    # simple routes that just map to $1.php
    rewrite ^/(archive|discover|profile|contact|rules|event|captcha|login|logout|privacy|transparency)/?$ /$1.php last;

    # routes for users
    rewrite ^/user/([^/]+)/?$ /user.php?user=$1 last;
    rewrite ^/user/([^/]+)/([^/]+)/?$ /user.php?user=$1&q=$2 last;

    # routes for pastes
    rewrite ^/([0-9]+)/report$ /report.php?id=$1 last;
    rewrite ^/([0-9]+)$ /paste.php?id=$1 last;
    rewrite ^/(download|raw|embed)/(.+)$ /paste.php?$1&id=$2 last;

    # weird registration routes that use a URL parameter rather than a different page (FIXME)
    rewrite ^/register$ /login.php?register last;
    rewrite ^/forgot$ /login.php?forgot last;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        # regex to split $uri to $fastcgi_script_name and $fastcgi_path
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;

        # Check that the PHP script exists before passing it
        try_files $fastcgi_script_name =404;

        # Bypass the fact that try_files resets $fastcgi_path_info
        # see: http://trac.nginx.org/nginx/ticket/321
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;

        fastcgi_index index.php;
        include fastcgi.conf;

        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
    }

    # Deny directories that should not be publicly accessible.
    location ~ (/doc|/tmp|/includes|/config|/\.git|/\.ht|/js|/node_modules|/composer).* {
        deny all;
    }
}
